/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.services.syncstorage.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param lastUpdate 
 */


data class HealthStatusResponse (

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "last_update")
    val lastUpdate: java.time.OffsetDateTime? = null

) {


}

