/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.services.syncstorage.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param autoTestExternalId 
 * @param statusCode 
 * @param statusType 
 * @param startedOn 
 */


data class TestResultCutApiModel (

    @Json(name = "projectId")
    val projectId: kotlin.String? = null,

    @Json(name = "autoTestExternalId")
    val autoTestExternalId: kotlin.String? = null,

    @Json(name = "statusCode")
    val statusCode: kotlin.String? = null,

    @Json(name = "statusType")
    val statusType: kotlin.String? = null,

    @Json(name = "startedOn")
    val startedOn: java.time.OffsetDateTime? = null

) {


}

