/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.services.syncstorage.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.services.syncstorage.models.CompletionResponse

import ru.testit.services.syncstorage.infrastructure.ApiClient
import ru.testit.services.syncstorage.infrastructure.ApiResponse
import ru.testit.services.syncstorage.infrastructure.ClientException
import ru.testit.services.syncstorage.infrastructure.ClientError
import ru.testit.services.syncstorage.infrastructure.ServerException
import ru.testit.services.syncstorage.infrastructure.ServerError
import ru.testit.services.syncstorage.infrastructure.MultiValueMap
import ru.testit.services.syncstorage.infrastructure.RequestConfig
import ru.testit.services.syncstorage.infrastructure.RequestMethod
import ru.testit.services.syncstorage.infrastructure.ResponseType
import ru.testit.services.syncstorage.infrastructure.Success

open class CompletionApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * GET /force-completion
     * Force completion of a test run
     *  Force processing completion for a specific test run.
     * @param testRunId Test Run ID
     * @return CompletionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun forceCompletionGet(testRunId: kotlin.String) : CompletionResponse {
        val localVarResponse = forceCompletionGetWithHttpInfo(testRunId = testRunId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CompletionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /force-completion
     * Force completion of a test run
     *  Force processing completion for a specific test run.
     * @param testRunId Test Run ID
     * @return ApiResponse<CompletionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun forceCompletionGetWithHttpInfo(testRunId: kotlin.String) : ApiResponse<CompletionResponse?> {
        val localVariableConfig = forceCompletionGetRequestConfig(testRunId = testRunId)

        return request<Unit, CompletionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation forceCompletionGet
     *
     * @param testRunId Test Run ID
     * @return RequestConfig
     */
    fun forceCompletionGetRequestConfig(testRunId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("testRunId", listOf(testRunId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/force-completion",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /wait-completion
     * Wait for completion
     *  Wait until processing is completed for a test run.
     * @param testRunId Test Run ID
     * @return CompletionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun waitCompletionGet(testRunId: kotlin.String) : CompletionResponse {
        val localVarResponse = waitCompletionGetWithHttpInfo(testRunId = testRunId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CompletionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /wait-completion
     * Wait for completion
     *  Wait until processing is completed for a test run.
     * @param testRunId Test Run ID
     * @return ApiResponse<CompletionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun waitCompletionGetWithHttpInfo(testRunId: kotlin.String) : ApiResponse<CompletionResponse?> {
        val localVariableConfig = waitCompletionGetRequestConfig(testRunId = testRunId)

        return request<Unit, CompletionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation waitCompletionGet
     *
     * @param testRunId Test Run ID
     * @return RequestConfig
     */
    fun waitCompletionGetRequestConfig(testRunId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("testRunId", listOf(testRunId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/wait-completion",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
