/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.services.syncstorage.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.services.syncstorage.models.TestResultCutApiModel
import ru.testit.services.syncstorage.models.TestResultSaveResponse

import ru.testit.services.syncstorage.infrastructure.ApiClient
import ru.testit.services.syncstorage.infrastructure.ApiResponse
import ru.testit.services.syncstorage.infrastructure.ClientException
import ru.testit.services.syncstorage.infrastructure.ClientError
import ru.testit.services.syncstorage.infrastructure.ServerException
import ru.testit.services.syncstorage.infrastructure.ServerError
import ru.testit.services.syncstorage.infrastructure.MultiValueMap
import ru.testit.services.syncstorage.infrastructure.RequestConfig
import ru.testit.services.syncstorage.infrastructure.RequestMethod
import ru.testit.services.syncstorage.infrastructure.ResponseType
import ru.testit.services.syncstorage.infrastructure.Success

open class TestResultsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /in_progress_test_result
     * Save in-progress test result
     *  Save a test result with InProgress status.
     * @param testRunId Test Run ID
     * @param testResultCutApiModel 
     * @return TestResultSaveResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun inProgressTestResultPost(testRunId: kotlin.String, testResultCutApiModel: TestResultCutApiModel) : TestResultSaveResponse {
        val localVarResponse = inProgressTestResultPostWithHttpInfo(testRunId = testRunId, testResultCutApiModel = testResultCutApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TestResultSaveResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /in_progress_test_result
     * Save in-progress test result
     *  Save a test result with InProgress status.
     * @param testRunId Test Run ID
     * @param testResultCutApiModel 
     * @return ApiResponse<TestResultSaveResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun inProgressTestResultPostWithHttpInfo(testRunId: kotlin.String, testResultCutApiModel: TestResultCutApiModel) : ApiResponse<TestResultSaveResponse?> {
        val localVariableConfig = inProgressTestResultPostRequestConfig(testRunId = testRunId, testResultCutApiModel = testResultCutApiModel)

        return request<TestResultCutApiModel, TestResultSaveResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation inProgressTestResultPost
     *
     * @param testRunId Test Run ID
     * @param testResultCutApiModel 
     * @return RequestConfig
     */
    fun inProgressTestResultPostRequestConfig(testRunId: kotlin.String, testResultCutApiModel: TestResultCutApiModel) : RequestConfig<TestResultCutApiModel> {
        val localVariableBody = testResultCutApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("testRunId", listOf(testRunId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/in_progress_test_result",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
