/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.services.syncstorage.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.services.syncstorage.models.RegisterRequest
import ru.testit.services.syncstorage.models.RegisterResponse
import ru.testit.services.syncstorage.models.SetWorkerStatusRequest
import ru.testit.services.syncstorage.models.SetWorkerStatusResponse

import ru.testit.services.syncstorage.infrastructure.ApiClient
import ru.testit.services.syncstorage.infrastructure.ApiResponse
import ru.testit.services.syncstorage.infrastructure.ClientException
import ru.testit.services.syncstorage.infrastructure.ClientError
import ru.testit.services.syncstorage.infrastructure.ServerException
import ru.testit.services.syncstorage.infrastructure.ServerError
import ru.testit.services.syncstorage.infrastructure.MultiValueMap
import ru.testit.services.syncstorage.infrastructure.RequestConfig
import ru.testit.services.syncstorage.infrastructure.RequestMethod
import ru.testit.services.syncstorage.infrastructure.ResponseType
import ru.testit.services.syncstorage.infrastructure.Success

open class WorkersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /register
     * Register a new worker
     *  Register a new worker with the sync storage service.
     * @param registerRequest 
     * @return RegisterResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun registerPost(registerRequest: RegisterRequest) : RegisterResponse {
        val localVarResponse = registerPostWithHttpInfo(registerRequest = registerRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RegisterResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /register
     * Register a new worker
     *  Register a new worker with the sync storage service.
     * @param registerRequest 
     * @return ApiResponse<RegisterResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun registerPostWithHttpInfo(registerRequest: RegisterRequest) : ApiResponse<RegisterResponse?> {
        val localVariableConfig = registerPostRequestConfig(registerRequest = registerRequest)

        return request<RegisterRequest, RegisterResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registerPost
     *
     * @param registerRequest 
     * @return RequestConfig
     */
    fun registerPostRequestConfig(registerRequest: RegisterRequest) : RequestConfig<RegisterRequest> {
        val localVariableBody = registerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/register",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /set_worker_status
     * Set worker status
     *  Set the status of a worker by its PID.
     * @param setWorkerStatusRequest 
     * @return SetWorkerStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setWorkerStatusPost(setWorkerStatusRequest: SetWorkerStatusRequest) : SetWorkerStatusResponse {
        val localVarResponse = setWorkerStatusPostWithHttpInfo(setWorkerStatusRequest = setWorkerStatusRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SetWorkerStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /set_worker_status
     * Set worker status
     *  Set the status of a worker by its PID.
     * @param setWorkerStatusRequest 
     * @return ApiResponse<SetWorkerStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setWorkerStatusPostWithHttpInfo(setWorkerStatusRequest: SetWorkerStatusRequest) : ApiResponse<SetWorkerStatusResponse?> {
        val localVariableConfig = setWorkerStatusPostRequestConfig(setWorkerStatusRequest = setWorkerStatusRequest)

        return request<SetWorkerStatusRequest, SetWorkerStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setWorkerStatusPost
     *
     * @param setWorkerStatusRequest 
     * @return RequestConfig
     */
    fun setWorkerStatusPostRequestConfig(setWorkerStatusRequest: SetWorkerStatusRequest) : RequestConfig<SetWorkerStatusRequest> {
        val localVariableBody = setWorkerStatusRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, text/plain"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/set_worker_status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
